version: '3.1'

services:
  cassandra:
    image: cassandra:3.2
    ports:
      - '9042:9042'

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  elasticsearch:
    image: elasticsearch:6.8.5
    ports:
    - '9200:9200'
    - '9300:9300'
    environment:
      discovery.type: single-node