version: '3.1'

services:
  cassandra:
    image: cassandra:3.2
    ports:
      - '9042:9042'
    volumes:
      - cassandra-volume:/var/lib/cassandra

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3307:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:6.8.5
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      discovery.type: single-node
volumes:
  mysql-volume:
  cassandra-volume: